package image

import (
	"context"
	"fmt"
	"path"
	"strings"
)

// The modular kernel drivers we bake into the guest rootfs. The extracted vmlinux
// boots WITHOUT them (Ubuntu ships them as CONFIG=m modules, not built-ins) and
// the cloud squashfs carries an EMPTY /lib/modules (the matching linux-modules
// package was never installed into it), so each would otherwise be missing:
//   - virtio_rng — CONFIG_HW_RANDOM_VIRTIO=m. /dev/hwrng exists but never binds, so
//     the entropy device provision-vm.py attaches can't feed the guest CSPRNG.
//   - zfs (+ its sole dep spl) — CONFIG_ZFS=m. `modprobe zfs` is FATAL, which aborts
//     bench-cli's ZFS volume step at boot. Ubuntu ships a PREBUILT zfs.ko in
//     linux-modules-<kver> matched to this exact kernel, so we bake that instead of
//     DKMS-compiling it every bake (DKMS pulls a toolchain + headers and burns
//     minutes of CPU). The kernel is byte-pinned by the dated cloud release, so its
//     vermagic never drifts out from under the prebuilt module.
//
// All three files live in the SAME linux-modules-<kver> deb, so one download seeds
// both drivers. We locate each by NAME/SUBTREE, not a hard-coded path, so a moved
// subdir or changed compression suffix (.ko.zst vs .ko.xz) still resolves.
const (
	virtioRngModule = "virtio_rng" // modprobe name (underscore); file is virtio-rng.ko*
	// zfs.ko depends only on spl.ko (icp/zavl/zcommon/… are compiled into the
	// monolithic Ubuntu zfs.ko); both sit under kernel/zfs/, so we copy that whole
	// subtree and let depmod resolve the zfs->spl edge from the modules' own
	// `depends=` modinfo.
	zfsModule  = "zfs"
	zfsSubtree = "kernel/zfs" // holds zfs.ko* and spl.ko* in linux-modules-<kver>
)

// moduleMetadata is the depmod metadata read alongside the .ko to emit a
// warning-free modules.dep; it ships in the same deb. modules.dep itself is
// generated by depmod, not copied.
var moduleMetadata = []string{"modules.builtin", "modules.builtin.modinfo", "modules.order"}

// zfsLoadUnit loads zfs.ko OFF the pre-sysinit serial chain but still eagerly and
// deterministically at every boot — including a plain reboot of a live site VM,
// where nothing (ssh, bench-cli, a login) can be assumed to run before the pool is
// needed. Pinning zfs in /etc/modules-load.d makes systemd-modules-load.service
// (Before=sysinit.target) insert the 6.6 MB zfs.ko before sysinit → basic →
// network → ssh, so ~0.9 s of module insertion serially gates time-to-SSH for a
// module nothing on that path touches. This oneshot instead inserts zfs.ko in
// PARALLEL with the rest of early userspace:
//   - WantedBy=sysinit.target — systemd ALWAYS pulls it in at boot (no reliance on
//     ssh/bench/login ever running first); reboot-safe on a live site VM.
//   - DefaultDependencies=no — opt out of the implicit After=sysinit.target that
//     would otherwise push it PAST sysinit (and thus past network/ssh).
//   - Deliberately NO `Before=sysinit.target` — that is exactly what makes
//     systemd-modules-load gate ssh; omitting it means sysinit does NOT wait on us.
//   - Before=zfs-import.target — still ordered AHEAD of the pool import, so the
//     module is guaranteed present before bench-cli imports the pool.
//
// ExecStartPost chmods /dev/zfs to 0666. Ubuntu's ZFS ships a udev rule
// (`90-zfs.rules`: `KERNEL=="zfs", MODE="0666"`) whose ONLY job for a dataset-only
// pool is to relax /dev/zfs from its kernel-default 0600 root:root so NON-ROOT
// `zfs`/`zpool` queries work. bench-cli's build runs some `zfs get` calls as the
// unprivileged `frappe` user, which fail with "the ZFS utilities must be run as
// root" if /dev/zfs stays 0600. We mask systemd-udevd (fixed virtio topology needs
// no rule-based device mgmt), so that udev rule never runs — we reproduce its one
// effect here, tied exactly to when the node appears (right after modprobe). No
// zvols are used (pool is dataset-only), so the rule's /dev/zvol handling is moot.
const zfsLoadUnit = `[Unit]
Description=Load the ZFS kernel module (off the pre-sysinit serial boot path)
DefaultDependencies=no
Before=zfs-import.target
Wants=zfs-import.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/modprobe zfs
ExecStartPost=/bin/chmod 0666 /dev/zfs

[Install]
WantedBy=sysinit.target
`

// manifestURLFor derives the cloud image's package manifest URL: the same URL with
// `.squashfs` swapped for `.manifest`. It pins the exact linux-modules-<kver>
// version, which is how the running kernel version is derived instead of
// hard-coded (a point-release bump moves both the kernel we boot and the module we
// must match, in lockstep). A non-squashfs rootfs has no sibling manifest; the
// empty return is the caller's "skip the module bake, no kver to match".
func manifestURLFor(rootfsURL string) string {
	if strings.HasSuffix(rootfsURL, ".squashfs") {
		return rootfsURL[:len(rootfsURL)-len(".squashfs")] + ".manifest"
	}
	return ""
}

// installGuestModules bakes the modular drivers the Firecracker guest needs
// (virtio_rng, zfs) into the rootfs, since it boots an external vmlinux against an
// empty /lib/modules. We fetch the manifest-pinned linux-modules-<kver> package
// ONCE, `dpkg-deb -x` it to a scratch dir, copy ONLY the modules we need + the
// depmod metadata into the rootfs, run depmod, and pin loading. Copying a handful
// of .ko files rather than `dpkg -i`-ing the whole ~32 MB module set keeps every
// guest ext4 (and its CoW snapshots) lean.
func installGuestModules(ctx context.Context, cmd commands, root, rootfsURL string) error {
	manifestURL := manifestURLFor(rootfsURL)
	if manifestURL == "" {
		return nil // "No sibling manifest for this rootfs; skipping guest module bake."
	}

	// 1. Derive the kernel version from the manifest's linux-modules-<kver> line.
	//    `linux-modules-6.8.0-117-generic\t6.8.0-117.117` -> kver 6.8.0-117-generic.
	manifest, err := cmd.Run(ctx, "curl -fsSL {}", manifestURL)
	if err != nil {
		return err
	}
	kver := ""
	for _, line := range strings.Split(manifest, "\n") {
		pkg := strings.TrimSpace(strings.SplitN(line, "\t", 2)[0])
		if strings.HasPrefix(pkg, "linux-modules-") && strings.HasSuffix(pkg, "-generic") {
			kver = pkg[len("linux-modules-"):]
			break
		}
	}
	if kver == "" {
		return fmt.Errorf("no linux-modules-*-generic entry in manifest %s", manifestURL)
	}

	// 2. Download the linux-modules deb into a scratch dir and unpack it with
	//    dpkg-deb -x (lays down its own lib/modules/<kver> tree; we copy out of it,
	//    never installing the full set). apt-get download resolves the exact archive
	//    URL/version from the host's apt metadata, writing to CWD.
	work := "/tmp/atlas-modules-" + kver
	debRoot := work + "/deb"
	if _, err := cmd.Run(ctx, "sudo rm -rf {}", work); err != nil {
		return err
	}
	if err := cmd.InstallDirectory(ctx, work, "0755"); err != nil {
		return err
	}
	if _, err := cmd.Shell(ctx, "cd {} && apt-get download {}", work, "linux-modules-"+kver); err != nil {
		return err
	}
	listing, err := cmd.Shell(ctx, "ls {}/linux-modules-{}_*.deb", work, kver)
	if err != nil {
		return err
	}
	deb := strings.SplitN(strings.TrimSpace(listing), "\n", 2)[0]
	if _, err := cmd.Run(ctx, "sudo dpkg-deb -x {} {}", deb, debRoot); err != nil {
		return err
	}

	sourceModules := debRoot + "/lib/modules/" + kver
	destModules := root + "/lib/modules/" + kver

	// 3. Copy virtio_rng by NAME (find, not a hard-coded path) into the SAME relative
	//    location under the rootfs so depmod records the path it actually lives at.
	//    The basename is virtio-rng.ko, virtio-rng.ko.zst, virtio-rng.ko.xz, …
	virtioRngFile := strings.ReplaceAll(virtioRngModule, "_", "-") + ".ko*"
	moduleSource, err := cmd.Shell(ctx, "find {} -name {} | head -1", sourceModules, virtioRngFile)
	if err != nil {
		return err
	}
	moduleSource = strings.TrimSpace(moduleSource)
	if moduleSource == "" {
		return fmt.Errorf("%s not found in linux-modules-%s", virtioRngModule, kver)
	}
	relative := moduleSource[len(sourceModules)+1:] // kernel/drivers/.../virtio-rng.ko.zst
	moduleDest := destModules + "/" + relative
	if err := cmd.InstallDirectory(ctx, path.Dir(moduleDest), "0755"); err != nil {
		return err
	}
	if _, err := cmd.Run(ctx, "sudo cp {} {}", moduleSource, moduleDest); err != nil {
		return err
	}

	// 4. Copy the whole kernel/zfs/ subtree (zfs.ko* + spl.ko*) verbatim so depmod
	//    resolves the zfs->spl dependency edge. cp -a preserves the subdir layout the
	//    module paths in modules.dep will reference.
	zfsSource := sourceModules + "/" + zfsSubtree
	found, err := cmd.Shell(ctx, "find {} -name {} | head -1", zfsSource, zfsModule+".ko*")
	if err != nil {
		return err
	}
	if strings.TrimSpace(found) == "" {
		return fmt.Errorf("%s not found under %s in linux-modules-%s", zfsModule, zfsSubtree, kver)
	}
	if err := cmd.InstallDirectory(ctx, destModules+"/"+path.Dir(zfsSubtree), "0755"); err != nil {
		return err
	}
	if _, err := cmd.Run(ctx, "sudo cp -a {} {}", zfsSource, destModules+"/"+zfsSubtree); err != nil {
		return err
	}

	// 5. Copy the depmod metadata that ships in the deb (modules.dep itself is
	//    generated by depmod below, not copied).
	for _, metadata := range moduleMetadata {
		if _, err := cmd.Run(ctx, "sudo cp {} {}", sourceModules+"/"+metadata, destModules+"/"+metadata); err != nil {
			return err
		}
	}

	// 6. Generate modules.dep for the rootfs tree so `modprobe <name>` resolves.
	//    -b <root> makes depmod treat the rootfs as / and read the metadata above.
	if _, err := cmd.Run(ctx, "sudo depmod -b {} {}", root, kver); err != nil {
		return err
	}

	// 7. Wire up loading. virtio_rng and zfs load by DIFFERENT paths on purpose:
	//
	//    * virtio_rng — pinned in /etc/modules-load.d so systemd-modules-load loads it
	//      eagerly before sysinit.target. It MUST bind early: it backs the /dev/hwrng
	//      the host feeds, and the guest CSPRNG seeds from it at boot. It is 12 KB —
	//      trivial to insert — so keeping it on the eager path costs nothing and buys
	//      early entropy. No udev autoload, hence the explicit pin.
	//    * zfs (6.6 MB) — loaded by atlas-zfs-load.service instead, OFF the
	//      pre-sysinit serial chain (see zfsLoadUnit). Pinning it here too would re-add
	//      the ~0.9 s zfs.ko insertion to systemd-modules-load, which gates sshd — the
	//      exact cost we are removing. The oneshot still guarantees zfs is present
	//      before the pool import, and is reboot-safe.
	if err := cmd.InstallDirectory(ctx, root+"/etc/modules-load.d", "0755"); err != nil {
		return err
	}
	if err := cmd.InstallFile(ctx, virtioRngModule+"\n", root+"/etc/modules-load.d/atlas-guest-modules.conf", "0644"); err != nil {
		return err
	}
	if err := cmd.InstallFile(ctx, zfsLoadUnit, root+"/etc/systemd/system/atlas-zfs-load.service", "0644"); err != nil {
		return err
	}
	if err := cmd.InstallDirectory(ctx, root+"/etc/systemd/system/sysinit.target.wants", "0755"); err != nil {
		return err
	}
	if _, err := cmd.Run(
		ctx, "sudo ln -sf /etc/systemd/system/atlas-zfs-load.service {}",
		root+"/etc/systemd/system/sysinit.target.wants/atlas-zfs-load.service",
	); err != nil {
		return err
	}

	_, err = cmd.Run(ctx, "sudo rm -rf {}", work)
	return err
}
