//go:build go1.22

// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package wire

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerTokenScopes = "bearerToken.Scopes"
)

// Defines values for DesiredPower.
const (
	DesiredPowerRunning DesiredPower = "Running"
	DesiredPowerStopped DesiredPower = "Stopped"
)

// Defines values for ErrorReason.
const (
	ErrorReasonNoFence                     ErrorReason = "no-fence"
	ErrorReasonOperationIdentifierConflict ErrorReason = "operation-identifier-conflict"
	ErrorReasonStaleFence                  ErrorReason = "stale-fence"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Defines values for OperationStatus.
const (
	OperationStatusFailure OperationStatus = "Failure"
	OperationStatusRunning OperationStatus = "Running"
	OperationStatusSuccess OperationStatus = "Success"
)

// Defines values for VirtualMachineStatus.
const (
	VirtualMachineStatusFailed   VirtualMachineStatus = "Failed"
	VirtualMachineStatusPaused   VirtualMachineStatus = "Paused"
	VirtualMachineStatusRunning  VirtualMachineStatus = "Running"
	VirtualMachineStatusSleeping VirtualMachineStatus = "Sleeping"
	VirtualMachineStatusStopped  VirtualMachineStatus = "Stopped"
	VirtualMachineStatusUnknown  VirtualMachineStatus = "Unknown"
)

// DesiredPower The only power input Boat's reconciler takes. An explicit Stopped
// outranks a wake trap: a VM that was told to stop is not woken by
// traffic.
type DesiredPower string

// DesiredVirtualMachine defines model for DesiredVirtualMachine.
type DesiredVirtualMachine struct {
	// BootEpoch Monotonic per-VM fence, issued only by Atlas and bumped at exactly
	// one point: a migration's repoint. Boat refuses to boot a UUID whose
	// local epoch is older than the one on disk, which is what stops two
	// live copies of one VM after a partition.
	//
	// Epochs start at 1. Boat gates on whether it holds a fence at all, so
	// a zero would be a held fence rather than the absence of one — do not
	// use 0 to mean unfenced.
	BootEpoch         int64   `json:"boot_epoch"`
	CpuMaxCores       *int    `json:"cpu_max_cores,omitempty"`
	CpuMode           *string `json:"cpu_mode,omitempty"`
	DataDiskGigabytes *int    `json:"data_disk_gigabytes,omitempty"`

	// DesiredPower The only power input Boat's reconciler takes. An explicit Stopped
	// outranks a wake trap: a VM that was told to stop is not woken by
	// traffic.
	DesiredPower       DesiredPower `json:"desired_power"`
	DiskGigabytes      *int         `json:"disk_gigabytes,omitempty"`
	IdleTimeoutSeconds *int         `json:"idle_timeout_seconds,omitempty"`
	Ipv6Address        *string      `json:"ipv6_address,omitempty"`
	MacAddress         *string      `json:"mac_address,omitempty"`
	MemoryMegabytes    *int         `json:"memory_megabytes,omitempty"`
	PrivateAddress     *string      `json:"private_address,omitempty"`

	// SleepOnIdle Enrolment, not policy. Boat runs the sleep reflex; whether a VM is
	// enrolled in it is Atlas's decision and arrives here.
	SleepOnIdle *bool   `json:"sleep_on_idle,omitempty"`
	TapDevice   *string `json:"tap_device,omitempty"`
	Uuid        string  `json:"uuid"`
	Vcpus       *int    `json:"vcpus,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Error What went wrong, in one sentence, at the boundary where it was detected.
	Error string `json:"error"`

	// Reason A stable token for the cases a caller must tell apart by code rather
	// than by prose. Absent when the sentence is the whole answer.
	Reason *ErrorReason `json:"reason,omitempty"`
}

// ErrorReason A stable token for the cases a caller must tell apart by code rather
// than by prose. Absent when the sentence is the whole answer.
type ErrorReason string

// Export defines model for Export.
type Export struct {
	// FenceEpochs Every fence this host holds, by UUID.
	FenceEpochs    *map[string]int64 `json:"fence_epochs,omitempty"`
	Host           HostFacts         `json:"host"`
	LogicalVolumes *[]LogicalVolume  `json:"logical_volumes,omitempty"`

	// ObservedEpoch Monotonic, bumped on every observed change. A CAS write is matched
	// against this, so a caller acts on exactly the snapshot it read.
	ObservedEpoch int64 `json:"observed_epoch"`

	// Quarantine Artifact sets this host holds that could not be read as a coherent
	// VM. Reported so an operator can resolve them; never acted upon, and
	// never counted as a VM.
	Quarantine *[]Quarantine `json:"quarantine,omitempty"`

	// TakenAt Always UTC, with a trailing Z. A naive stamp cannot be ordered across hosts.
	TakenAt time.Time `json:"taken_at"`

	// Units The sibling units this Boat supervises, and whether they are up.
	Units           *[]UnitLiveness  `json:"units,omitempty"`
	VirtualMachines []VirtualMachine `json:"virtual_machines"`
}

// Health defines model for Health.
type Health struct {
	// BoatVersion The version of the running binary — every unit on this host is this build.
	BoatVersion string       `json:"boat_version"`
	Status      HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Host defines model for Host.
type Host struct {
	BoatVersion string `json:"boat_version"`
	Hostname    string `json:"hostname"`

	// StartedAt When this daemon process started. A restart is visible here.
	StartedAt time.Time `json:"started_at"`

	// VirtualMachineCount How many VMs this host currently observes.
	VirtualMachineCount int `json:"virtual_machine_count"`
}

// HostFacts defines model for HostFacts.
type HostFacts struct {
	BoatVersion        string  `json:"boat_version"`
	FirecrackerVersion *string `json:"firecracker_version,omitempty"`

	// HostSignature Identifies the CPU, kernel and Firecracker a memory snapshot was
	// captured on. A snapshot only restores on a matching host.
	HostSignature          *string  `json:"host_signature,omitempty"`
	Hostname               string   `json:"hostname"`
	KernelVersion          *string  `json:"kernel_version,omitempty"`
	MemoryMegabytesFree    *int     `json:"memory_megabytes_free,omitempty"`
	MemoryMegabytesTotal   *int     `json:"memory_megabytes_total,omitempty"`
	PoolDiskGigabytesTotal *int     `json:"pool_disk_gigabytes_total,omitempty"`
	PoolUsedPercent        *float32 `json:"pool_used_percent,omitempty"`
	VcpusTotal             *int     `json:"vcpus_total,omitempty"`
}

// LogicalVolume defines model for LogicalVolume.
type LogicalVolume struct {
	Name string `json:"name"`

	// Origin Set when this volume is a snapshot or a clone of another.
	Origin    *string `json:"origin,omitempty"`
	Pool      *string `json:"pool,omitempty"`
	SizeBytes *int64  `json:"size_bytes,omitempty"`
}

// Operation defines model for Operation.
type Operation struct {
	EndedAt *time.Time `json:"ended_at,omitempty"`

	// Error Set when status is Failure. The failure, stated once.
	Error *string `json:"error,omitempty"`

	// ExitCode 0 on success. Mirrors the exit code the equivalent Task carried.
	//
	// Absent means the operation has not finished — an operation still
	// Running has no exit code, and reporting 0 for one would tell a
	// client it succeeded. Any terminal operation carries this field.
	ExitCode *int `json:"exit_code,omitempty"`

	// OperationId Equal to the Atlas Task name that drove this operation.
	OperationId string `json:"operation_id"`

	// Output The operation's combined trace and output — the same text a Task row's
	// stdout carries today, so the operator surface is unchanged.
	Output    *string         `json:"output,omitempty"`
	StartedAt time.Time       `json:"started_at"`
	Status    OperationStatus `json:"status"`
	Uuid      string          `json:"uuid"`

	// Verb The verb that ran, in the host CLI's grammar (start-vm, stop-vm).
	Verb string `json:"verb"`
}

// OperationStatus defines model for OperationStatus.
type OperationStatus string

// Quarantine defines model for Quarantine.
type Quarantine struct {
	// Evidence The observations that made it ambiguous rather than simply absent.
	Evidence *[]string `json:"evidence,omitempty"`

	// Identifier Whatever the host retained to name this artifact set — usually a VM
	// UUID, but a stranded namespace or address keeps only its own name,
	// and inventing a UUID for it would be a guess.
	Identifier string `json:"identifier"`

	// Reason What was incoherent, in one sentence.
	Reason string     `json:"reason"`
	SeenAt *time.Time `json:"seen_at,omitempty"`
}

// StartRequest defines model for StartRequest.
type StartRequest struct {
	// OperationId The Atlas Task name. Re-posting one returns its recorded result.
	OperationId string `json:"operation_id"`
}

// StopRequest defines model for StopRequest.
type StopRequest struct {
	// Graceful Ask the guest to power itself off first, so anything dirty in its page
	// cache is written. False discards guest RAM — for callers that capture
	// the disk another way, such as a migration cold stop.
	Graceful    *bool  `json:"graceful,omitempty"`
	OperationId string `json:"operation_id"`

	// StopTimeoutSeconds Bound the graceful drain without skipping the unit's ExecStopPost.
	// 0 leaves systemd's default drain in place.
	StopTimeoutSeconds *int `json:"stop_timeout_seconds,omitempty"`
}

// UnitLiveness defines model for UnitLiveness.
type UnitLiveness struct {
	ActiveState string `json:"active_state"`
	Name        string `json:"name"`
	SubState    string `json:"sub_state"`
}

// VirtualMachine defines model for VirtualMachine.
type VirtualMachine struct {
	// BootEpoch The fence epoch this host is permitted to boot the VM at. Absent
	// means Boat holds no fence for it and will refuse to start it.
	BootEpoch *int64 `json:"boot_epoch,omitempty"`

	// FirecrackerPid The running Firecracker process, when Boat has re-attached to one.
	// Absent means no live process was found, not that the VM is dead.
	FirecrackerPid *int `json:"firecracker_pid,omitempty"`

	// HasMemorySnapshot A complete memory snapshot is staged, so the next start resumes from RAM.
	HasMemorySnapshot         *bool     `json:"has_memory_snapshot,omitempty"`
	ObservedAt                time.Time `json:"observed_at"`
	ObservedDataDiskGigabytes *int      `json:"observed_data_disk_gigabytes,omitempty"`
	ObservedDiskGigabytes     *int      `json:"observed_disk_gigabytes,omitempty"`
	ObservedMemoryMegabytes   *int      `json:"observed_memory_megabytes,omitempty"`

	// ObservedStatus Boat's observed status, derived from the host — the unit's state and the
	// on-disk markers — never from a command's success.
	ObservedStatus VirtualMachineStatus `json:"observed_status"`
	ObservedVcpus  *int                 `json:"observed_vcpus,omitempty"`

	// QuarantineReason What was incoherent, in one sentence.
	QuarantineReason *string `json:"quarantine_reason,omitempty"`

	// Quarantined The host holds artifacts for this VM that Boat could not read as a
	// coherent state — a crash part-way through a terminate, say. It is
	// reported, never silently ingested as truth, and never acted upon
	// until a human or Atlas resolves it.
	Quarantined *bool `json:"quarantined,omitempty"`

	// Sleeping The sleeping marker is present — the VM is parked, not stopped.
	Sleeping *bool `json:"sleeping,omitempty"`

	// UnitActiveState The systemd ActiveState of firecracker-vm@<uuid>.service, verbatim.
	UnitActiveState *string `json:"unit_active_state,omitempty"`

	// UnitSubState The systemd SubState of the unit, verbatim.
	UnitSubState *string `json:"unit_sub_state,omitempty"`
	Uuid         string  `json:"uuid"`
}

// VirtualMachineStatus Boat's observed status, derived from the host — the unit's state and the
// on-disk markers — never from a command's success.
type VirtualMachineStatus string

// VirtualMachineUuid defines model for VirtualMachineUuid.
type VirtualMachineUuid = string

// NotFound defines model for NotFound.
type NotFound = Error

// OperationAccepted defines model for OperationAccepted.
type OperationAccepted = Operation

// OperationIdentifierConflict defines model for OperationIdentifierConflict.
type OperationIdentifierConflict = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PutVirtualMachineJSONRequestBody defines body for PutVirtualMachine for application/json ContentType.
type PutVirtualMachineJSONRequestBody = DesiredVirtualMachine

// StartVirtualMachineJSONRequestBody defines body for StartVirtualMachine for application/json ContentType.
type StartVirtualMachineJSONRequestBody = StartRequest

// StopVirtualMachineJSONRequestBody defines body for StopVirtualMachine for application/json ContentType.
type StopVirtualMachineJSONRequestBody = StopRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// This host's entire observed state, in one document
	// (GET /export)
	GetExport(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Host facts and the running Boat version
	// (GET /host)
	GetHost(w http.ResponseWriter, r *http.Request)
	// One operation's journal record
	// (GET /ops/{operation_id})
	GetOperation(w http.ResponseWriter, r *http.Request, operationId string)
	// List every VM this host observes
	// (GET /vms)
	ListVirtualMachines(w http.ResponseWriter, r *http.Request)
	// Observed state of one VM
	// (GET /vms/{uuid})
	GetVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Assert this VM's desired state
	// (PUT /vms/{uuid})
	PutVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Start a provisioned VM
	// (POST /vms/{uuid}/start)
	StartVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Stop a running VM
	// (POST /vms/{uuid}/stop)
	StopVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Stream observed changes as they happen
	// (GET /watch)
	Watch(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetExport operation middleware
func (siw *ServerInterfaceWrapper) GetExport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHost operation middleware
func (siw *ServerInterfaceWrapper) GetHost(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId string

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperation(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVirtualMachines(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) PutVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) StartVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) StopVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Watch operation middleware
func (siw *ServerInterfaceWrapper) Watch(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Watch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/export", wrapper.GetExport)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/host", wrapper.GetHost)
	m.HandleFunc("GET "+options.BaseURL+"/ops/{operation_id}", wrapper.GetOperation)
	m.HandleFunc("GET "+options.BaseURL+"/vms", wrapper.ListVirtualMachines)
	m.HandleFunc("GET "+options.BaseURL+"/vms/{uuid}", wrapper.GetVirtualMachine)
	m.HandleFunc("PUT "+options.BaseURL+"/vms/{uuid}", wrapper.PutVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/start", wrapper.StartVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/stop", wrapper.StopVirtualMachine)
	m.HandleFunc("GET "+options.BaseURL+"/watch", wrapper.Watch)

	return m
}

type NotFoundJSONResponse Error

type OperationAcceptedJSONResponse Operation

type OperationIdentifierConflictJSONResponse Error

type UnauthorizedJSONResponse Error

type GetExportRequestObject struct {
}

type GetExportResponseObject interface {
	VisitGetExportResponse(w http.ResponseWriter) error
}

type GetExport200JSONResponse Export

func (response GetExport200JSONResponse) VisitGetExportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetExport401JSONResponse) VisitGetExportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHostRequestObject struct {
}

type GetHostResponseObject interface {
	VisitGetHostResponse(w http.ResponseWriter) error
}

type GetHost200JSONResponse Host

func (response GetHost200JSONResponse) VisitGetHostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHost401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHost401JSONResponse) VisitGetHostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationRequestObject struct {
	OperationId string `json:"operation_id"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse Operation

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOperation401JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListVirtualMachinesRequestObject struct {
}

type ListVirtualMachinesResponseObject interface {
	VisitListVirtualMachinesResponse(w http.ResponseWriter) error
}

type ListVirtualMachines200JSONResponse []VirtualMachine

func (response ListVirtualMachines200JSONResponse) VisitListVirtualMachinesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListVirtualMachines401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListVirtualMachines401JSONResponse) VisitListVirtualMachinesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
}

type GetVirtualMachineResponseObject interface {
	VisitGetVirtualMachineResponse(w http.ResponseWriter) error
}

type GetVirtualMachine200JSONResponse VirtualMachine

func (response GetVirtualMachine200JSONResponse) VisitGetVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetVirtualMachine401JSONResponse) VisitGetVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVirtualMachine404JSONResponse) VisitGetVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *PutVirtualMachineJSONRequestBody
}

type PutVirtualMachineResponseObject interface {
	VisitPutVirtualMachineResponse(w http.ResponseWriter) error
}

type PutVirtualMachine200JSONResponse DesiredVirtualMachine

func (response PutVirtualMachine200JSONResponse) VisitPutVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutVirtualMachine401JSONResponse) VisitPutVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutVirtualMachine409JSONResponse Error

func (response PutVirtualMachine409JSONResponse) VisitPutVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type StartVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *StartVirtualMachineJSONRequestBody
}

type StartVirtualMachineResponseObject interface {
	VisitStartVirtualMachineResponse(w http.ResponseWriter) error
}

type StartVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response StartVirtualMachine200JSONResponse) VisitStartVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StartVirtualMachine401JSONResponse) VisitStartVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StartVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response StartVirtualMachine404JSONResponse) VisitStartVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartVirtualMachine409JSONResponse Error

func (response StartVirtualMachine409JSONResponse) VisitStartVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type StopVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *StopVirtualMachineJSONRequestBody
}

type StopVirtualMachineResponseObject interface {
	VisitStopVirtualMachineResponse(w http.ResponseWriter) error
}

type StopVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response StopVirtualMachine200JSONResponse) VisitStopVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StopVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StopVirtualMachine401JSONResponse) VisitStopVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StopVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response StopVirtualMachine404JSONResponse) VisitStopVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StopVirtualMachine409JSONResponse struct {
	OperationIdentifierConflictJSONResponse
}

func (response StopVirtualMachine409JSONResponse) VisitStopVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type WatchRequestObject struct {
}

type WatchResponseObject interface {
	VisitWatchResponse(w http.ResponseWriter) error
}

type Watch200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response Watch200TexteventStreamResponse) VisitWatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type Watch401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Watch401JSONResponse) VisitWatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// This host's entire observed state, in one document
	// (GET /export)
	GetExport(ctx context.Context, request GetExportRequestObject) (GetExportResponseObject, error)
	// Liveness probe
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Host facts and the running Boat version
	// (GET /host)
	GetHost(ctx context.Context, request GetHostRequestObject) (GetHostResponseObject, error)
	// One operation's journal record
	// (GET /ops/{operation_id})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)
	// List every VM this host observes
	// (GET /vms)
	ListVirtualMachines(ctx context.Context, request ListVirtualMachinesRequestObject) (ListVirtualMachinesResponseObject, error)
	// Observed state of one VM
	// (GET /vms/{uuid})
	GetVirtualMachine(ctx context.Context, request GetVirtualMachineRequestObject) (GetVirtualMachineResponseObject, error)
	// Assert this VM's desired state
	// (PUT /vms/{uuid})
	PutVirtualMachine(ctx context.Context, request PutVirtualMachineRequestObject) (PutVirtualMachineResponseObject, error)
	// Start a provisioned VM
	// (POST /vms/{uuid}/start)
	StartVirtualMachine(ctx context.Context, request StartVirtualMachineRequestObject) (StartVirtualMachineResponseObject, error)
	// Stop a running VM
	// (POST /vms/{uuid}/stop)
	StopVirtualMachine(ctx context.Context, request StopVirtualMachineRequestObject) (StopVirtualMachineResponseObject, error)
	// Stream observed changes as they happen
	// (GET /watch)
	Watch(ctx context.Context, request WatchRequestObject) (WatchResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetExport operation middleware
func (sh *strictHandler) GetExport(w http.ResponseWriter, r *http.Request) {
	var request GetExportRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExport(ctx, request.(GetExportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExportResponseObject); ok {
		if err := validResponse.VisitGetExportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHost operation middleware
func (sh *strictHandler) GetHost(w http.ResponseWriter, r *http.Request) {
	var request GetHostRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHost(ctx, request.(GetHostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHost")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHostResponseObject); ok {
		if err := validResponse.VisitGetHostResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(w http.ResponseWriter, r *http.Request, operationId string) {
	var request GetOperationRequestObject

	request.OperationId = operationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVirtualMachines operation middleware
func (sh *strictHandler) ListVirtualMachines(w http.ResponseWriter, r *http.Request) {
	var request ListVirtualMachinesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVirtualMachines(ctx, request.(ListVirtualMachinesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVirtualMachines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVirtualMachinesResponseObject); ok {
		if err := validResponse.VisitListVirtualMachinesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVirtualMachine operation middleware
func (sh *strictHandler) GetVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request GetVirtualMachineRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVirtualMachine(ctx, request.(GetVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVirtualMachineResponseObject); ok {
		if err := validResponse.VisitGetVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutVirtualMachine operation middleware
func (sh *strictHandler) PutVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request PutVirtualMachineRequestObject

	request.Uuid = uuid

	var body PutVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutVirtualMachine(ctx, request.(PutVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutVirtualMachineResponseObject); ok {
		if err := validResponse.VisitPutVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartVirtualMachine operation middleware
func (sh *strictHandler) StartVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request StartVirtualMachineRequestObject

	request.Uuid = uuid

	var body StartVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartVirtualMachine(ctx, request.(StartVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartVirtualMachineResponseObject); ok {
		if err := validResponse.VisitStartVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopVirtualMachine operation middleware
func (sh *strictHandler) StopVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request StopVirtualMachineRequestObject

	request.Uuid = uuid

	var body StopVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopVirtualMachine(ctx, request.(StopVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopVirtualMachineResponseObject); ok {
		if err := validResponse.VisitStopVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Watch operation middleware
func (sh *strictHandler) Watch(w http.ResponseWriter, r *http.Request) {
	var request WatchRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Watch(ctx, request.(WatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Watch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WatchResponseObject); ok {
		if err := validResponse.VisitWatchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
