//go:build go1.22

// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package wire

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerTokenScopes = "bearerToken.Scopes"
)

// Defines values for DesiredPower.
const (
	DesiredPowerRunning DesiredPower = "Running"
	DesiredPowerStopped DesiredPower = "Stopped"
)

// Defines values for ErrorReason.
const (
	ErrorReasonNoFence                     ErrorReason = "no-fence"
	ErrorReasonOperationIdentifierConflict ErrorReason = "operation-identifier-conflict"
	ErrorReasonStaleFence                  ErrorReason = "stale-fence"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Defines values for OperationStatus.
const (
	OperationStatusFailure OperationStatus = "Failure"
	OperationStatusRunning OperationStatus = "Running"
	OperationStatusSuccess OperationStatus = "Success"
)

// Defines values for VirtualMachineStatus.
const (
	VirtualMachineStatusFailed   VirtualMachineStatus = "Failed"
	VirtualMachineStatusPaused   VirtualMachineStatus = "Paused"
	VirtualMachineStatusRunning  VirtualMachineStatus = "Running"
	VirtualMachineStatusSleeping VirtualMachineStatus = "Sleeping"
	VirtualMachineStatusStopped  VirtualMachineStatus = "Stopped"
	VirtualMachineStatusUnknown  VirtualMachineStatus = "Unknown"
)

// DesiredPower The only power input Boat's reconciler takes. An explicit Stopped
// outranks a wake trap: a VM that was told to stop is not woken by
// traffic.
type DesiredPower string

// DesiredVirtualMachine defines model for DesiredVirtualMachine.
type DesiredVirtualMachine struct {
	// BootEpoch Monotonic per-VM fence, issued only by Atlas and bumped at exactly
	// one point: a migration's repoint. Boat refuses to boot a UUID whose
	// local epoch is older than the one on disk, which is what stops two
	// live copies of one VM after a partition.
	//
	// Epochs start at 1. Boat gates on whether it holds a fence at all, so
	// a zero would be a held fence rather than the absence of one — do not
	// use 0 to mean unfenced.
	BootEpoch int64 `json:"boot_epoch"`

	// CpuMaxCores A number, not an integer: a share of a core is a real product. Atlas
	// sells fractional CPU (a Shared 1x VM gets a quarter of a core), its
	// own field is a float, and Python's JSON encoder always writes a
	// float with a decimal point — which Go refuses to decode into an
	// integer, even for 1.0. Typed as an integer, this rejected every
	// desired-state assertion Atlas could send, for every VM.
	CpuMaxCores       *float32 `json:"cpu_max_cores,omitempty"`
	CpuMode           *string  `json:"cpu_mode,omitempty"`
	DataDiskGigabytes *int     `json:"data_disk_gigabytes,omitempty"`

	// DesiredPower The only power input Boat's reconciler takes. An explicit Stopped
	// outranks a wake trap: a VM that was told to stop is not woken by
	// traffic.
	DesiredPower       DesiredPower `json:"desired_power"`
	DiskGigabytes      *int         `json:"disk_gigabytes,omitempty"`
	IdleTimeoutSeconds *int         `json:"idle_timeout_seconds,omitempty"`
	Ipv6Address        *string      `json:"ipv6_address,omitempty"`
	MacAddress         *string      `json:"mac_address,omitempty"`
	MemoryMegabytes    *int         `json:"memory_megabytes,omitempty"`
	PrivateAddress     *string      `json:"private_address,omitempty"`

	// SleepOnIdle Enrolment, not policy. Boat runs the sleep reflex; whether a VM is
	// enrolled in it is Atlas's decision and arrives here.
	SleepOnIdle *bool   `json:"sleep_on_idle,omitempty"`
	TapDevice   *string `json:"tap_device,omitempty"`
	Uuid        string  `json:"uuid"`
	Vcpus       *int    `json:"vcpus,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Error What went wrong, in one sentence, at the boundary where it was detected.
	Error string `json:"error"`

	// Reason A stable token for the cases a caller must tell apart by code rather
	// than by prose. Absent when the sentence is the whole answer.
	Reason *ErrorReason `json:"reason,omitempty"`
}

// ErrorReason A stable token for the cases a caller must tell apart by code rather
// than by prose. Absent when the sentence is the whole answer.
type ErrorReason string

// Export defines model for Export.
type Export struct {
	// FenceEpochs Every fence this host holds, by UUID.
	FenceEpochs    *map[string]int64 `json:"fence_epochs,omitempty"`
	Host           HostFacts         `json:"host"`
	LogicalVolumes *[]LogicalVolume  `json:"logical_volumes,omitempty"`

	// ObservedEpoch Monotonic, bumped on every observed change. A CAS write is matched
	// against this, so a caller acts on exactly the snapshot it read.
	ObservedEpoch int64 `json:"observed_epoch"`

	// Quarantine Artifact sets this host holds that could not be read as a coherent
	// VM. Reported so an operator can resolve them; never acted upon, and
	// never counted as a VM.
	Quarantine *[]Quarantine `json:"quarantine,omitempty"`

	// TakenAt Always UTC, with a trailing Z. A naive stamp cannot be ordered across hosts.
	TakenAt time.Time `json:"taken_at"`

	// Units The sibling units this Boat supervises, and whether they are up.
	Units           *[]UnitLiveness  `json:"units,omitempty"`
	VirtualMachines []VirtualMachine `json:"virtual_machines"`
}

// GuestFile defines model for GuestFile.
type GuestFile struct {
	// Content The file's bytes, written as they arrived.
	Content string `json:"content"`

	// Path An absolute path inside the guest. It is joined onto the host's
	// mount point, so a relative path or one containing `..` is refused
	// rather than sanitised — it would write on the host, as root.
	Path string `json:"path"`
}

// GuestIdentity What makes a freshly laid-down root filesystem this VM's rather than the
// image's. Boat writes every field of it into the mounted filesystem
// without interpreting any of it: an address is bytes it puts in a file,
// an authorized-keys blob is a blob, and `extra_env` is a list of paths
// and contents Boat cannot tell apart from one another.
//
// Hostname and machine-id are deliberately absent. Boat derives both from
// the UUID by a fixed rule it owns, because naming a host after its UUID
// is mechanics rather than identity, and a value sent for them could
// disagree with the one the host already uses.
type GuestIdentity struct {
	// AuthorizedKeysBlob The guest's root authorized_keys file, whole and verbatim. One key
	// or six, and whose they are, is not legible from here and is not
	// Boat's business.
	AuthorizedKeysBlob *string `json:"authorized_keys_blob,omitempty"`

	// DataDiskMountAt Where the data disk is mounted in the guest, so the fresh rootfs
	// regains its fstab line. Empty means no data mount and no line.
	DataDiskMountAt *string `json:"data_disk_mount_at,omitempty"`

	// ExtraEnv Every other file the control plane wants in the fresh rootfs. This
	// is the guest-service seam: a field named for what a file MEANS would
	// put a service semantic into Boat's vocabulary and make the host care
	// what runs inside the guest, so the files arrive anonymous.
	ExtraEnv    *[]GuestFile `json:"extra_env,omitempty"`
	Ipv4Gateway *string      `json:"ipv4_gateway,omitempty"`

	// Ipv4GuestCidr The guest's end of the NAT44 /30 it egresses through. The host's end
	// is not here: a rebuild does not touch host-side networking, so the
	// value would be accepted and ignored.
	Ipv4GuestCidr *string `json:"ipv4_guest_cidr,omitempty"`
	Ipv6Address   *string `json:"ipv6_address,omitempty"`

	// PrivateAddress The VM's /128 on the host mesh, empty for a VM off the private
	// plane. The line is written either way, so the guest's network unit
	// has a defined value to test rather than a missing variable.
	PrivateAddress *string `json:"private_address,omitempty"`
}

// Health defines model for Health.
type Health struct {
	// BoatVersion The version of the running binary — every unit on this host is this build.
	BoatVersion string       `json:"boat_version"`
	Status      HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Host defines model for Host.
type Host struct {
	BoatVersion string `json:"boat_version"`
	Hostname    string `json:"hostname"`

	// StartedAt When this daemon process started. A restart is visible here.
	StartedAt time.Time `json:"started_at"`

	// VirtualMachineCount How many VMs this host currently observes.
	VirtualMachineCount int `json:"virtual_machine_count"`
}

// HostFacts defines model for HostFacts.
type HostFacts struct {
	BoatVersion        string  `json:"boat_version"`
	FirecrackerVersion *string `json:"firecracker_version,omitempty"`

	// HostSignature Identifies the CPU, kernel and Firecracker a memory snapshot was
	// captured on. A snapshot only restores on a matching host.
	HostSignature          *string  `json:"host_signature,omitempty"`
	Hostname               string   `json:"hostname"`
	KernelVersion          *string  `json:"kernel_version,omitempty"`
	MemoryMegabytesFree    *int     `json:"memory_megabytes_free,omitempty"`
	MemoryMegabytesTotal   *int     `json:"memory_megabytes_total,omitempty"`
	PoolDiskGigabytesTotal *int     `json:"pool_disk_gigabytes_total,omitempty"`
	PoolUsedPercent        *float32 `json:"pool_used_percent,omitempty"`
	VcpusTotal             *int     `json:"vcpus_total,omitempty"`
}

// LogicalVolume defines model for LogicalVolume.
type LogicalVolume struct {
	Name string `json:"name"`

	// Origin Set when this volume is a snapshot or a clone of another.
	Origin    *string `json:"origin,omitempty"`
	Pool      *string `json:"pool,omitempty"`
	SizeBytes *int64  `json:"size_bytes,omitempty"`
}

// Operation defines model for Operation.
type Operation struct {
	EndedAt *time.Time `json:"ended_at,omitempty"`

	// Error Set when status is Failure. The failure, stated once.
	Error *string `json:"error,omitempty"`

	// ExitCode 0 on success. Mirrors the exit code the equivalent Task carried.
	//
	// Absent means the operation has not finished — an operation still
	// Running has no exit code, and reporting 0 for one would tell a
	// client it succeeded. Any terminal operation carries this field.
	ExitCode *int `json:"exit_code,omitempty"`

	// OperationId Equal to the Atlas Task name that drove this operation.
	OperationId string `json:"operation_id"`

	// Output The operation's combined trace and output — the same text a Task row's
	// stdout carries today, so the operator surface is unchanged.
	Output    *string         `json:"output,omitempty"`
	StartedAt time.Time       `json:"started_at"`
	Status    OperationStatus `json:"status"`
	Uuid      string          `json:"uuid"`

	// Verb The verb that ran, in the host CLI's grammar (start-vm, stop-vm).
	Verb string `json:"verb"`
}

// OperationRequest defines model for OperationRequest.
type OperationRequest struct {
	// OperationId The Atlas Task name. Re-posting one returns its recorded result
	// rather than running the verb again.
	OperationId string `json:"operation_id"`
}

// OperationStatus defines model for OperationStatus.
type OperationStatus string

// Quarantine defines model for Quarantine.
type Quarantine struct {
	// Evidence The observations that made it ambiguous rather than simply absent.
	Evidence *[]string `json:"evidence,omitempty"`

	// Identifier Whatever the host retained to name this artifact set — usually a VM
	// UUID, but a stranded namespace or address keeps only its own name,
	// and inventing a UUID for it would be a guess.
	Identifier string `json:"identifier"`

	// Reason What was incoherent, in one sentence.
	Reason string     `json:"reason"`
	SeenAt *time.Time `json:"seen_at,omitempty"`
}

// RebuildRequest defines model for RebuildRequest.
type RebuildRequest struct {
	// DataSnapshotDevice The data disk's own snapshot, restored the way the root disk is.
	// Absent leaves the live data disk exactly as it is — a rebuild from
	// an image always does, because there is no image source for a data
	// disk, and wiping a tenant's home directory because they asked to
	// reinstall the operating system is not a default.
	DataSnapshotDevice *string `json:"data_snapshot_device,omitempty"`

	// Identity What makes a freshly laid-down root filesystem this VM's rather than the
	// image's. Boat writes every field of it into the mounted filesystem
	// without interpreting any of it: an address is bytes it puts in a file,
	// an authorized-keys blob is a blob, and `extra_env` is a list of paths
	// and contents Boat cannot tell apart from one another.
	//
	// Hostname and machine-id are deliberately absent. Boat derives both from
	// the UUID by a fixed rule it owns, because naming a host after its UUID
	// is mechanics rather than identity, and a value sent for them could
	// disagree with the one the host already uses.
	Identity *GuestIdentity `json:"identity,omitempty"`

	// Image A base image already synced to this host, whose pristine rootfs the
	// new root filesystem is a copy-on-write snapshot of.
	Image *string `json:"image,omitempty"`

	// OperationId The Atlas Task name. Re-posting one returns its recorded result.
	OperationId string `json:"operation_id"`

	// SnapshotDevice The device path of a snapshot volume on this host to restore from,
	// instead of an image. Exactly one source is needed; this one wins
	// when both are given.
	SnapshotDevice *string `json:"snapshot_device,omitempty"`
}

// StartRequest defines model for StartRequest.
type StartRequest struct {
	// OperationId The Atlas Task name. Re-posting one returns its recorded result.
	OperationId string `json:"operation_id"`
}

// StopRequest defines model for StopRequest.
type StopRequest struct {
	// Graceful Ask the guest to power itself off first, so anything dirty in its page
	// cache is written. False discards guest RAM — for callers that capture
	// the disk another way, such as a migration cold stop.
	Graceful    *bool  `json:"graceful,omitempty"`
	OperationId string `json:"operation_id"`

	// StopTimeoutSeconds Bound the graceful drain without skipping the unit's ExecStopPost.
	// 0 leaves systemd's default drain in place.
	StopTimeoutSeconds *int `json:"stop_timeout_seconds,omitempty"`
}

// UnitLiveness defines model for UnitLiveness.
type UnitLiveness struct {
	ActiveState string `json:"active_state"`
	Name        string `json:"name"`
	SubState    string `json:"sub_state"`
}

// VirtualMachine defines model for VirtualMachine.
type VirtualMachine struct {
	// FirecrackerPid The process that answered on this VM's API socket. A diagnostic that
	// lets an operator strace the right process, and nothing more: the
	// liveness claim is that the socket answered, so an absent pid — no
	// live Firecracker, or one whose socket holder `ss` could not name —
	// says nothing on its own about observed_status.
	FirecrackerPid *int `json:"firecracker_pid,omitempty"`

	// HasMemorySnapshot A complete memory snapshot is staged, so the next start resumes from RAM.
	HasMemorySnapshot *bool     `json:"has_memory_snapshot,omitempty"`
	ObservedAt        time.Time `json:"observed_at"`

	// ObservedStatus Boat's observed status, derived from the host — the unit's state and the
	// on-disk markers — never from a command's success.
	ObservedStatus VirtualMachineStatus `json:"observed_status"`

	// Sleeping The sleeping marker is present — the VM is parked, not stopped.
	Sleeping *bool `json:"sleeping,omitempty"`

	// UnitActiveState The systemd ActiveState of firecracker-vm@<uuid>.service, verbatim.
	UnitActiveState *string `json:"unit_active_state,omitempty"`

	// UnitSubState The systemd SubState of the unit, verbatim.
	UnitSubState *string `json:"unit_sub_state,omitempty"`
	Uuid         string  `json:"uuid"`
}

// VirtualMachineStatus Boat's observed status, derived from the host — the unit's state and the
// on-disk markers — never from a command's success.
type VirtualMachineStatus string

// VirtualMachineUuid defines model for VirtualMachineUuid.
type VirtualMachineUuid = string

// NotFound defines model for NotFound.
type NotFound = Error

// OperationAccepted defines model for OperationAccepted.
type OperationAccepted = Operation

// OperationIdentifierConflict defines model for OperationIdentifierConflict.
type OperationIdentifierConflict = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PutVirtualMachineJSONRequestBody defines body for PutVirtualMachine for application/json ContentType.
type PutVirtualMachineJSONRequestBody = DesiredVirtualMachine

// PauseVirtualMachineJSONRequestBody defines body for PauseVirtualMachine for application/json ContentType.
type PauseVirtualMachineJSONRequestBody = OperationRequest

// RebuildVirtualMachineJSONRequestBody defines body for RebuildVirtualMachine for application/json ContentType.
type RebuildVirtualMachineJSONRequestBody = RebuildRequest

// ResizeVirtualMachineJSONRequestBody defines body for ResizeVirtualMachine for application/json ContentType.
type ResizeVirtualMachineJSONRequestBody = OperationRequest

// ResumeVirtualMachineJSONRequestBody defines body for ResumeVirtualMachine for application/json ContentType.
type ResumeVirtualMachineJSONRequestBody = OperationRequest

// SleepVirtualMachineJSONRequestBody defines body for SleepVirtualMachine for application/json ContentType.
type SleepVirtualMachineJSONRequestBody = OperationRequest

// StartVirtualMachineJSONRequestBody defines body for StartVirtualMachine for application/json ContentType.
type StartVirtualMachineJSONRequestBody = StartRequest

// StopVirtualMachineJSONRequestBody defines body for StopVirtualMachine for application/json ContentType.
type StopVirtualMachineJSONRequestBody = StopRequest

// TerminateVirtualMachineJSONRequestBody defines body for TerminateVirtualMachine for application/json ContentType.
type TerminateVirtualMachineJSONRequestBody = OperationRequest

// WakeVirtualMachineJSONRequestBody defines body for WakeVirtualMachine for application/json ContentType.
type WakeVirtualMachineJSONRequestBody = OperationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// This host's entire observed state, in one document
	// (GET /export)
	GetExport(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Host facts and the running Boat version
	// (GET /host)
	GetHost(w http.ResponseWriter, r *http.Request)
	// One operation's journal record
	// (GET /ops/{operation_id})
	GetOperation(w http.ResponseWriter, r *http.Request, operationId string)
	// List every VM this host observes
	// (GET /vms)
	ListVirtualMachines(w http.ResponseWriter, r *http.Request)
	// Observed state of one VM
	// (GET /vms/{uuid})
	GetVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Assert this VM's desired state
	// (PUT /vms/{uuid})
	PutVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Pause a running guest
	// (POST /vms/{uuid}/pause)
	PauseVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Rebuild a VM's root disk from an image or a snapshot
	// (POST /vms/{uuid}/rebuild)
	RebuildVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Resize a stopped VM
	// (POST /vms/{uuid}/resize)
	ResizeVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Resume a paused guest
	// (POST /vms/{uuid}/resume)
	ResumeVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Park a VM to free its RAM
	// (POST /vms/{uuid}/sleep)
	SleepVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Start a provisioned VM
	// (POST /vms/{uuid}/start)
	StartVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Stop a running VM
	// (POST /vms/{uuid}/stop)
	StopVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Destroy a VM and everything it holds on this host
	// (POST /vms/{uuid}/terminate)
	TerminateVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Wake a sleeping VM now
	// (POST /vms/{uuid}/wake)
	WakeVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid)
	// Stream observed changes as they happen
	// (GET /watch)
	Watch(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetExport operation middleware
func (siw *ServerInterfaceWrapper) GetExport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHost operation middleware
func (siw *ServerInterfaceWrapper) GetHost(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId string

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperation(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVirtualMachines(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) PutVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PauseVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) PauseVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PauseVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RebuildVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) RebuildVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RebuildVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResizeVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) ResizeVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResizeVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) ResumeVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SleepVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) SleepVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SleepVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) StartVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) StopVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TerminateVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) TerminateVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TerminateVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WakeVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) WakeVirtualMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid VirtualMachineUuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WakeVirtualMachine(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Watch operation middleware
func (siw *ServerInterfaceWrapper) Watch(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Watch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/export", wrapper.GetExport)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/host", wrapper.GetHost)
	m.HandleFunc("GET "+options.BaseURL+"/ops/{operation_id}", wrapper.GetOperation)
	m.HandleFunc("GET "+options.BaseURL+"/vms", wrapper.ListVirtualMachines)
	m.HandleFunc("GET "+options.BaseURL+"/vms/{uuid}", wrapper.GetVirtualMachine)
	m.HandleFunc("PUT "+options.BaseURL+"/vms/{uuid}", wrapper.PutVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/pause", wrapper.PauseVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/rebuild", wrapper.RebuildVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/resize", wrapper.ResizeVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/resume", wrapper.ResumeVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/sleep", wrapper.SleepVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/start", wrapper.StartVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/stop", wrapper.StopVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/terminate", wrapper.TerminateVirtualMachine)
	m.HandleFunc("POST "+options.BaseURL+"/vms/{uuid}/wake", wrapper.WakeVirtualMachine)
	m.HandleFunc("GET "+options.BaseURL+"/watch", wrapper.Watch)

	return m
}

type NotFoundJSONResponse Error

type OperationAcceptedJSONResponse Operation

type OperationIdentifierConflictJSONResponse Error

type UnauthorizedJSONResponse Error

type GetExportRequestObject struct {
}

type GetExportResponseObject interface {
	VisitGetExportResponse(w http.ResponseWriter) error
}

type GetExport200JSONResponse Export

func (response GetExport200JSONResponse) VisitGetExportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetExport401JSONResponse) VisitGetExportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHostRequestObject struct {
}

type GetHostResponseObject interface {
	VisitGetHostResponse(w http.ResponseWriter) error
}

type GetHost200JSONResponse Host

func (response GetHost200JSONResponse) VisitGetHostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHost401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHost401JSONResponse) VisitGetHostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationRequestObject struct {
	OperationId string `json:"operation_id"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse Operation

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOperation401JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListVirtualMachinesRequestObject struct {
}

type ListVirtualMachinesResponseObject interface {
	VisitListVirtualMachinesResponse(w http.ResponseWriter) error
}

type ListVirtualMachines200JSONResponse []VirtualMachine

func (response ListVirtualMachines200JSONResponse) VisitListVirtualMachinesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListVirtualMachines401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListVirtualMachines401JSONResponse) VisitListVirtualMachinesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
}

type GetVirtualMachineResponseObject interface {
	VisitGetVirtualMachineResponse(w http.ResponseWriter) error
}

type GetVirtualMachine200JSONResponse VirtualMachine

func (response GetVirtualMachine200JSONResponse) VisitGetVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetVirtualMachine401JSONResponse) VisitGetVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVirtualMachine404JSONResponse) VisitGetVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *PutVirtualMachineJSONRequestBody
}

type PutVirtualMachineResponseObject interface {
	VisitPutVirtualMachineResponse(w http.ResponseWriter) error
}

type PutVirtualMachine200JSONResponse DesiredVirtualMachine

func (response PutVirtualMachine200JSONResponse) VisitPutVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutVirtualMachine401JSONResponse) VisitPutVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutVirtualMachine409JSONResponse Error

func (response PutVirtualMachine409JSONResponse) VisitPutVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PauseVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *PauseVirtualMachineJSONRequestBody
}

type PauseVirtualMachineResponseObject interface {
	VisitPauseVirtualMachineResponse(w http.ResponseWriter) error
}

type PauseVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response PauseVirtualMachine200JSONResponse) VisitPauseVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PauseVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PauseVirtualMachine401JSONResponse) VisitPauseVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PauseVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response PauseVirtualMachine404JSONResponse) VisitPauseVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PauseVirtualMachine409JSONResponse struct {
	OperationIdentifierConflictJSONResponse
}

func (response PauseVirtualMachine409JSONResponse) VisitPauseVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RebuildVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *RebuildVirtualMachineJSONRequestBody
}

type RebuildVirtualMachineResponseObject interface {
	VisitRebuildVirtualMachineResponse(w http.ResponseWriter) error
}

type RebuildVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response RebuildVirtualMachine200JSONResponse) VisitRebuildVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RebuildVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RebuildVirtualMachine401JSONResponse) VisitRebuildVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RebuildVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response RebuildVirtualMachine404JSONResponse) VisitRebuildVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RebuildVirtualMachine409JSONResponse struct {
	OperationIdentifierConflictJSONResponse
}

func (response RebuildVirtualMachine409JSONResponse) VisitRebuildVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ResizeVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *ResizeVirtualMachineJSONRequestBody
}

type ResizeVirtualMachineResponseObject interface {
	VisitResizeVirtualMachineResponse(w http.ResponseWriter) error
}

type ResizeVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response ResizeVirtualMachine200JSONResponse) VisitResizeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResizeVirtualMachine400JSONResponse Error

func (response ResizeVirtualMachine400JSONResponse) VisitResizeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ResizeVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ResizeVirtualMachine401JSONResponse) VisitResizeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ResizeVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response ResizeVirtualMachine404JSONResponse) VisitResizeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResizeVirtualMachine409JSONResponse struct {
	OperationIdentifierConflictJSONResponse
}

func (response ResizeVirtualMachine409JSONResponse) VisitResizeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ResumeVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *ResumeVirtualMachineJSONRequestBody
}

type ResumeVirtualMachineResponseObject interface {
	VisitResumeVirtualMachineResponse(w http.ResponseWriter) error
}

type ResumeVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response ResumeVirtualMachine200JSONResponse) VisitResumeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResumeVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ResumeVirtualMachine401JSONResponse) VisitResumeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ResumeVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response ResumeVirtualMachine404JSONResponse) VisitResumeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResumeVirtualMachine409JSONResponse Error

func (response ResumeVirtualMachine409JSONResponse) VisitResumeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type SleepVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *SleepVirtualMachineJSONRequestBody
}

type SleepVirtualMachineResponseObject interface {
	VisitSleepVirtualMachineResponse(w http.ResponseWriter) error
}

type SleepVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response SleepVirtualMachine200JSONResponse) VisitSleepVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SleepVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SleepVirtualMachine401JSONResponse) VisitSleepVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SleepVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response SleepVirtualMachine404JSONResponse) VisitSleepVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SleepVirtualMachine409JSONResponse struct {
	OperationIdentifierConflictJSONResponse
}

func (response SleepVirtualMachine409JSONResponse) VisitSleepVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type StartVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *StartVirtualMachineJSONRequestBody
}

type StartVirtualMachineResponseObject interface {
	VisitStartVirtualMachineResponse(w http.ResponseWriter) error
}

type StartVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response StartVirtualMachine200JSONResponse) VisitStartVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StartVirtualMachine401JSONResponse) VisitStartVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StartVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response StartVirtualMachine404JSONResponse) VisitStartVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartVirtualMachine409JSONResponse Error

func (response StartVirtualMachine409JSONResponse) VisitStartVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type StopVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *StopVirtualMachineJSONRequestBody
}

type StopVirtualMachineResponseObject interface {
	VisitStopVirtualMachineResponse(w http.ResponseWriter) error
}

type StopVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response StopVirtualMachine200JSONResponse) VisitStopVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StopVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StopVirtualMachine401JSONResponse) VisitStopVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StopVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response StopVirtualMachine404JSONResponse) VisitStopVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StopVirtualMachine409JSONResponse struct {
	OperationIdentifierConflictJSONResponse
}

func (response StopVirtualMachine409JSONResponse) VisitStopVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type TerminateVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *TerminateVirtualMachineJSONRequestBody
}

type TerminateVirtualMachineResponseObject interface {
	VisitTerminateVirtualMachineResponse(w http.ResponseWriter) error
}

type TerminateVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response TerminateVirtualMachine200JSONResponse) VisitTerminateVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TerminateVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response TerminateVirtualMachine401JSONResponse) VisitTerminateVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type TerminateVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response TerminateVirtualMachine404JSONResponse) VisitTerminateVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TerminateVirtualMachine409JSONResponse struct {
	OperationIdentifierConflictJSONResponse
}

func (response TerminateVirtualMachine409JSONResponse) VisitTerminateVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type WakeVirtualMachineRequestObject struct {
	Uuid VirtualMachineUuid `json:"uuid"`
	Body *WakeVirtualMachineJSONRequestBody
}

type WakeVirtualMachineResponseObject interface {
	VisitWakeVirtualMachineResponse(w http.ResponseWriter) error
}

type WakeVirtualMachine200JSONResponse struct{ OperationAcceptedJSONResponse }

func (response WakeVirtualMachine200JSONResponse) VisitWakeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type WakeVirtualMachine401JSONResponse struct{ UnauthorizedJSONResponse }

func (response WakeVirtualMachine401JSONResponse) VisitWakeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type WakeVirtualMachine404JSONResponse struct{ NotFoundJSONResponse }

func (response WakeVirtualMachine404JSONResponse) VisitWakeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type WakeVirtualMachine409JSONResponse Error

func (response WakeVirtualMachine409JSONResponse) VisitWakeVirtualMachineResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type WatchRequestObject struct {
}

type WatchResponseObject interface {
	VisitWatchResponse(w http.ResponseWriter) error
}

type Watch200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response Watch200TexteventStreamResponse) VisitWatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type Watch401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Watch401JSONResponse) VisitWatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// This host's entire observed state, in one document
	// (GET /export)
	GetExport(ctx context.Context, request GetExportRequestObject) (GetExportResponseObject, error)
	// Liveness probe
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Host facts and the running Boat version
	// (GET /host)
	GetHost(ctx context.Context, request GetHostRequestObject) (GetHostResponseObject, error)
	// One operation's journal record
	// (GET /ops/{operation_id})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)
	// List every VM this host observes
	// (GET /vms)
	ListVirtualMachines(ctx context.Context, request ListVirtualMachinesRequestObject) (ListVirtualMachinesResponseObject, error)
	// Observed state of one VM
	// (GET /vms/{uuid})
	GetVirtualMachine(ctx context.Context, request GetVirtualMachineRequestObject) (GetVirtualMachineResponseObject, error)
	// Assert this VM's desired state
	// (PUT /vms/{uuid})
	PutVirtualMachine(ctx context.Context, request PutVirtualMachineRequestObject) (PutVirtualMachineResponseObject, error)
	// Pause a running guest
	// (POST /vms/{uuid}/pause)
	PauseVirtualMachine(ctx context.Context, request PauseVirtualMachineRequestObject) (PauseVirtualMachineResponseObject, error)
	// Rebuild a VM's root disk from an image or a snapshot
	// (POST /vms/{uuid}/rebuild)
	RebuildVirtualMachine(ctx context.Context, request RebuildVirtualMachineRequestObject) (RebuildVirtualMachineResponseObject, error)
	// Resize a stopped VM
	// (POST /vms/{uuid}/resize)
	ResizeVirtualMachine(ctx context.Context, request ResizeVirtualMachineRequestObject) (ResizeVirtualMachineResponseObject, error)
	// Resume a paused guest
	// (POST /vms/{uuid}/resume)
	ResumeVirtualMachine(ctx context.Context, request ResumeVirtualMachineRequestObject) (ResumeVirtualMachineResponseObject, error)
	// Park a VM to free its RAM
	// (POST /vms/{uuid}/sleep)
	SleepVirtualMachine(ctx context.Context, request SleepVirtualMachineRequestObject) (SleepVirtualMachineResponseObject, error)
	// Start a provisioned VM
	// (POST /vms/{uuid}/start)
	StartVirtualMachine(ctx context.Context, request StartVirtualMachineRequestObject) (StartVirtualMachineResponseObject, error)
	// Stop a running VM
	// (POST /vms/{uuid}/stop)
	StopVirtualMachine(ctx context.Context, request StopVirtualMachineRequestObject) (StopVirtualMachineResponseObject, error)
	// Destroy a VM and everything it holds on this host
	// (POST /vms/{uuid}/terminate)
	TerminateVirtualMachine(ctx context.Context, request TerminateVirtualMachineRequestObject) (TerminateVirtualMachineResponseObject, error)
	// Wake a sleeping VM now
	// (POST /vms/{uuid}/wake)
	WakeVirtualMachine(ctx context.Context, request WakeVirtualMachineRequestObject) (WakeVirtualMachineResponseObject, error)
	// Stream observed changes as they happen
	// (GET /watch)
	Watch(ctx context.Context, request WatchRequestObject) (WatchResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetExport operation middleware
func (sh *strictHandler) GetExport(w http.ResponseWriter, r *http.Request) {
	var request GetExportRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExport(ctx, request.(GetExportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExportResponseObject); ok {
		if err := validResponse.VisitGetExportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHost operation middleware
func (sh *strictHandler) GetHost(w http.ResponseWriter, r *http.Request) {
	var request GetHostRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHost(ctx, request.(GetHostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHost")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHostResponseObject); ok {
		if err := validResponse.VisitGetHostResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(w http.ResponseWriter, r *http.Request, operationId string) {
	var request GetOperationRequestObject

	request.OperationId = operationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVirtualMachines operation middleware
func (sh *strictHandler) ListVirtualMachines(w http.ResponseWriter, r *http.Request) {
	var request ListVirtualMachinesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVirtualMachines(ctx, request.(ListVirtualMachinesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVirtualMachines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVirtualMachinesResponseObject); ok {
		if err := validResponse.VisitListVirtualMachinesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVirtualMachine operation middleware
func (sh *strictHandler) GetVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request GetVirtualMachineRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVirtualMachine(ctx, request.(GetVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVirtualMachineResponseObject); ok {
		if err := validResponse.VisitGetVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutVirtualMachine operation middleware
func (sh *strictHandler) PutVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request PutVirtualMachineRequestObject

	request.Uuid = uuid

	var body PutVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutVirtualMachine(ctx, request.(PutVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutVirtualMachineResponseObject); ok {
		if err := validResponse.VisitPutVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PauseVirtualMachine operation middleware
func (sh *strictHandler) PauseVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request PauseVirtualMachineRequestObject

	request.Uuid = uuid

	var body PauseVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PauseVirtualMachine(ctx, request.(PauseVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PauseVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PauseVirtualMachineResponseObject); ok {
		if err := validResponse.VisitPauseVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RebuildVirtualMachine operation middleware
func (sh *strictHandler) RebuildVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request RebuildVirtualMachineRequestObject

	request.Uuid = uuid

	var body RebuildVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RebuildVirtualMachine(ctx, request.(RebuildVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RebuildVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RebuildVirtualMachineResponseObject); ok {
		if err := validResponse.VisitRebuildVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResizeVirtualMachine operation middleware
func (sh *strictHandler) ResizeVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request ResizeVirtualMachineRequestObject

	request.Uuid = uuid

	var body ResizeVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResizeVirtualMachine(ctx, request.(ResizeVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResizeVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResizeVirtualMachineResponseObject); ok {
		if err := validResponse.VisitResizeVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeVirtualMachine operation middleware
func (sh *strictHandler) ResumeVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request ResumeVirtualMachineRequestObject

	request.Uuid = uuid

	var body ResumeVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeVirtualMachine(ctx, request.(ResumeVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeVirtualMachineResponseObject); ok {
		if err := validResponse.VisitResumeVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SleepVirtualMachine operation middleware
func (sh *strictHandler) SleepVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request SleepVirtualMachineRequestObject

	request.Uuid = uuid

	var body SleepVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SleepVirtualMachine(ctx, request.(SleepVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SleepVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SleepVirtualMachineResponseObject); ok {
		if err := validResponse.VisitSleepVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartVirtualMachine operation middleware
func (sh *strictHandler) StartVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request StartVirtualMachineRequestObject

	request.Uuid = uuid

	var body StartVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartVirtualMachine(ctx, request.(StartVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartVirtualMachineResponseObject); ok {
		if err := validResponse.VisitStartVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopVirtualMachine operation middleware
func (sh *strictHandler) StopVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request StopVirtualMachineRequestObject

	request.Uuid = uuid

	var body StopVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopVirtualMachine(ctx, request.(StopVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopVirtualMachineResponseObject); ok {
		if err := validResponse.VisitStopVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TerminateVirtualMachine operation middleware
func (sh *strictHandler) TerminateVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request TerminateVirtualMachineRequestObject

	request.Uuid = uuid

	var body TerminateVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TerminateVirtualMachine(ctx, request.(TerminateVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TerminateVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TerminateVirtualMachineResponseObject); ok {
		if err := validResponse.VisitTerminateVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// WakeVirtualMachine operation middleware
func (sh *strictHandler) WakeVirtualMachine(w http.ResponseWriter, r *http.Request, uuid VirtualMachineUuid) {
	var request WakeVirtualMachineRequestObject

	request.Uuid = uuid

	var body WakeVirtualMachineJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WakeVirtualMachine(ctx, request.(WakeVirtualMachineRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WakeVirtualMachine")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WakeVirtualMachineResponseObject); ok {
		if err := validResponse.VisitWakeVirtualMachineResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Watch operation middleware
func (sh *strictHandler) Watch(w http.ResponseWriter, r *http.Request) {
	var request WatchRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Watch(ctx, request.(WatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Watch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WatchResponseObject); ok {
		if err := validResponse.VisitWatchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
