package provision

import (
	"fmt"
	"strings"

	"github.com/frappe/boat/internal/paths"
	"github.com/frappe/boat/internal/run"
)

// bootArgumentsBlock is the launcher's preamble, verbatim. Cold boot passes
// --config-file; when a complete memory snapshot is pending, Firecracker must
// start IDLE instead, which is why the array is emptied rather than extended.
const bootArgumentsBlock = `# Cold boot passes --config-file. When a complete memory snapshot is
# pending (marker written by snapshot-stop-vm.py, or staged from a warm
# golden by provision-vm.py), Firecracker must start IDLE instead —
# /snapshot/load is pre-boot only and cannot coexist with --config-file.
# vm-restore.py (ExecStartPost) then loads and resumes it. A warm clone's
# staged MMDS payload (metadata.json) rides --metadata on the cold path
# (so the cold-boot FALLBACK still adopts the clone identity); on the
# idle path vm-restore.py PUTs it over the API instead.
boot_args=(--config-file firecracker.json)
`

// jailerLaunch renders the per-VM jailer-launch.sh the systemd unit execs.
//
// The jailer command line is built HERE rather than inline in the unit's ExecStart
// because the --cgroup cpu.max value is "<quota> <period>" — an internal space the
// cgroup file format requires. systemd word-splits an unquoted $VAR in ExecStart on
// every space, which would shatter that value into a stray positional the jailer
// rejects ("Found argument '100000' …"). `exec` so the jailer is the unit's main
// PID (KillMode=mixed). It is regenerated on every (re)provision, so it stays in
// step with the row.
//
// THE TEXT IS THE CONTRACT, not just the arguments. Two other verbs read this file
// back: internal/vm's resize splices its `--cgroup <value> \` lines in place (and
// refuses a launcher with none, rather than leaving stale caps behind), and its
// sleep verb greps for `snapshot/READY` to tell a launcher that predates memory
// snapshots from one that supports them. The header names provision-vm.py because
// this is a byte-for-byte port of what that script writes, and a host carries VMs
// provisioned by both.
func jailerLaunch(params Params, virtualMachine paths.VirtualMachine) string {
	var launcher strings.Builder
	launcher.WriteString("#!/bin/bash\n")
	fmt.Fprintf(&launcher, "# GENERATED by provision-vm.py for VM %s. Do not edit.\n", params.VirtualMachineName)
	launcher.WriteString("set -euo pipefail\n\n")
	launcher.WriteString(bootArgumentsBlock)
	fmt.Fprintf(&launcher, "if [[ -f %s ]]; then\n", virtualMachine.MetadataFile())
	launcher.WriteString("    boot_args+=(--metadata metadata.json)\nfi\n")
	fmt.Fprintf(&launcher, "if [[ -f %s ]]; then\n", virtualMachine.MemorySnapshotMarker())
	launcher.WriteString("    boot_args=()\nfi\n\n")
	launcher.WriteString(strings.Join(jailerExec(params, virtualMachine), "\n"))
	launcher.WriteString("\n")
	return launcher.String()
}

// jailerExec is the backslash-continued exec, one argument per line.
//
// CRITICAL: each cgroup and resource token is run.Quote'd (shlex.quote), or bash
// would word-split "cpu.max=100000 100000" back into two arguments in this
// generated `exec` line — re-introducing the exact "Found argument '100000'" bug
// the shell's mapfile and "${cgroup_args[@]}" quoting existed to prevent. The
// constant flag is interleaved here rather than carried in the input, so the input
// is values only.
func jailerExec(params Params, virtualMachine paths.VirtualMachine) []string {
	lines := []string{
		`exec /usr/local/bin/jailer \`,
		"    --id " + params.VirtualMachineName + ` \`,
		`    --exec-file /usr/local/bin/firecracker \`,
		fmt.Sprintf("    --uid %d"+` \`, params.FirecrackerUID),
		fmt.Sprintf("    --gid %d"+` \`, params.FirecrackerUID),
		`    --cgroup-version 2 \`,
		"    --netns /var/run/netns/" + params.Namespace + ` \`,
	}
	for _, value := range params.CgroupArguments {
		lines = append(lines, "    --cgroup "+run.Quote(value)+` \`)
	}
	// An operator omitting --resource-arg on a hand run falls back to the constant
	// no-file limit, so the jail is still descriptor-bounded. The controller always
	// passes a non-empty set, so its path is unaffected.
	resourceArguments := params.ResourceArguments
	if len(resourceArguments) == 0 {
		resourceArguments = defaultResourceArguments
	}
	for _, value := range resourceArguments {
		lines = append(lines, "    --resource-limit "+run.Quote(value)+` \`)
	}
	return append(lines,
		"    --chroot-base-dir "+virtualMachine.JailChrootBase()+` \`,
		`    -- \`,
		`    --api-sock run/firecracker.socket \`,
		`    "${boot_args[@]}"`,
	)
}
