package provision

import (
	"strings"
	"testing"

	"github.com/frappe/boat/internal/paths"
)

// Every `want` in this file was CAPTURED FROM THE PYTHON: scripts/provision-vm.py
// was imported and its _firecracker_config / _network_env / _jailer_launch /
// _mmds_metadata called with testParams()'s values, and the output pasted below
// unchanged. These four files are what a VM boots from, so they are the port's
// conformance oracle, and a difference here is a VM that boots differently rather
// than a test that is merely out of date.

const wantFirecrackerConfiguration = `{
  "boot-source": {
    "kernel_image_path": "vmlinux",
    "boot_args": "8250.nr_uarts=0 reboot=k panic=1"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "rootfs.ext4",
      "is_root_device": true,
      "is_read_only": false
    }
  ],
  "network-interfaces": [
    {
      "iface_id": "eth0",
      "guest_mac": "06:00:01:02:03:04",
      "host_dev_name": "atlas-3f2504e0"
    }
  ],
  "machine-config": {
    "vcpu_count": 2,
    "mem_size_mib": 2048
  },
  "mmds-config": {
    "version": "V1",
    "network_interfaces": [
      "eth0"
    ]
  },
  "entropy": {}
}
`

// TestTheFirecrackerConfigIsThePythons. Byte-identical, indent included: this file
// is Firecracker's whole boot contract, and internal/vm's resize edits it in place
// with jq — a key that moved or a type that changed is a resize writing into a
// shape it does not recognise.
func TestTheFirecrackerConfigIsThePythons(t *testing.T) {
	got, err := firecrackerConfiguration(testParams())
	if err != nil {
		t.Fatalf("firecrackerConfiguration: %v", err)
	}
	assertText(t, got, wantFirecrackerConfiguration)
}

// TestADataDiskIsASecondNonRootDrive. Appended, never inserted, so an ordinary
// VM's config stays byte-identical to what it was before data disks existed —
// which is what lets one host carry VMs provisioned before and after the feature.
func TestADataDiskIsASecondNonRootDrive(t *testing.T) {
	params := testParams()
	params.DataDiskGB = 50

	got, err := firecrackerConfiguration(params)
	if err != nil {
		t.Fatalf("firecrackerConfiguration: %v", err)
	}

	want := strings.Replace(wantFirecrackerConfiguration, `      "is_read_only": false
    }
  ],
  "network-interfaces"`, `      "is_read_only": false
    },
    {
      "drive_id": "data",
      "path_on_host": "data.ext4",
      "is_root_device": false,
      "is_read_only": false
    }
  ],
  "network-interfaces"`, 1)
	assertText(t, got, want)
}

// TestTheNetworkEnvironmentIsThePythons. This sidecar is how a host rebuilds a
// VM's networking after a reboot with no database, so a missing or misspelled key
// is a VM that comes back with no route.
func TestTheNetworkEnvironmentIsThePythons(t *testing.T) {
	assertText(t, networkEnvironment(testParams()), `TAP_DEVICE=atlas-3f2504e0
VIRTUAL_MACHINE_IPV6=2001:db8::2
ATLAS_NETNS=atlas-3f2504e0ns
HOST_VETH=atlas-h3f2504
NAMESPACE_VETH=atlas-n3f2504
IPV4_HOST_CIDR=100.64.200.9/30
IPV4_GUEST_CIDR=100.64.200.10/30
ATLAS_FC_UID=255999
`)
}

// TestTheReservedIPAndPrivatePlaneAreAppendedWhenPresent. Both blocks are absent on
// an ordinary VM — vm-network-up reads them with a default and skips its 1:1-NAT
// and private-plane sections — so their presence is the whole of the switch.
func TestTheReservedIPAndPrivatePlaneAreAppendedWhenPresent(t *testing.T) {
	params := testParams()
	params.ReservedIPv4 = "203.0.113.7"
	params.PrivateAddress = "fdaa:1::5"
	params.TenantPrefix = "fdaa:1::/48"

	assertText(t, networkEnvironment(params), `TAP_DEVICE=atlas-3f2504e0
VIRTUAL_MACHINE_IPV6=2001:db8::2
ATLAS_NETNS=atlas-3f2504e0ns
HOST_VETH=atlas-h3f2504
NAMESPACE_VETH=atlas-n3f2504
IPV4_HOST_CIDR=100.64.200.9/30
IPV4_GUEST_CIDR=100.64.200.10/30
ATLAS_FC_UID=255999
RESERVED_IPV4=203.0.113.7
PRIVATE_ADDRESS=fdaa:1::5
TENANT_PREFIX=fdaa:1::/48
`)
}

// TestThePrivatePlaneNeedsBothHalves. vm-network-up gates its private block on
// PRIVATE_ADDRESS *and* TENANT_PREFIX, so writing one alone would leave a VM
// half-enrolled — an address with no tenant to be isolated within.
func TestThePrivatePlaneNeedsBothHalves(t *testing.T) {
	params := testParams()
	params.PrivateAddress = "fdaa:1::5"

	rendered := networkEnvironment(params)

	if strings.Contains(rendered, "PRIVATE_ADDRESS") {
		t.Errorf("a private address with no tenant prefix was written:\n%s", rendered)
	}
}

const wantJailerLaunch = `#!/bin/bash
# GENERATED by provision-vm.py for VM 3f2504e0-4f89-41d3-9a0c-0305e82c3301. Do not edit.
set -euo pipefail

# Cold boot passes --config-file. When a complete memory snapshot is
# pending (marker written by snapshot-stop-vm.py, or staged from a warm
# golden by provision-vm.py), Firecracker must start IDLE instead —
# /snapshot/load is pre-boot only and cannot coexist with --config-file.
# vm-restore.py (ExecStartPost) then loads and resumes it. A warm clone's
# staged MMDS payload (metadata.json) rides --metadata on the cold path
# (so the cold-boot FALLBACK still adopts the clone identity); on the
# idle path vm-restore.py PUTs it over the API instead.
boot_args=(--config-file firecracker.json)
if [[ -f ` + testJailRoot + `/metadata.json ]]; then
    boot_args+=(--metadata metadata.json)
fi
if [[ -f ` + testJailRoot + `/snapshot/READY ]]; then
    boot_args=()
fi

exec /usr/local/bin/jailer \
    --id 3f2504e0-4f89-41d3-9a0c-0305e82c3301 \
    --exec-file /usr/local/bin/firecracker \
    --uid 255999 \
    --gid 255999 \
    --cgroup-version 2 \
    --netns /var/run/netns/atlas-3f2504e0ns \
    --cgroup memory.max=2415919104 \
    --cgroup memory.swap.max=0 \
    --cgroup 'cpu.max=200000 100000' \
    --resource-limit no-file=1024 \
    --chroot-base-dir ` + testDirectory + `/jail \
    -- \
    --api-sock run/firecracker.socket \
    "${boot_args[@]}"
`

// TestTheLauncherIsThePythons. Note the third cgroup line: `cpu.max=200000 100000`
// carries an internal space the cgroup file format requires, and it comes out
// SINGLE-QUOTED. Without that quoting bash word-splits it back into two arguments
// in this generated exec and the jailer refuses to start ("Found argument
// '100000' …") — the exact bug the shell's mapfile dance existed to prevent.
func TestTheLauncherIsThePythons(t *testing.T) {
	assertText(t, jailerLaunch(testParams(), paths.ForVirtualMachine(testUUID)), wantJailerLaunch)
}

// TestResourceLimitsFallBackToTheConstant. An operator hand-running the verb omits
// --resource-arg; the jail must still be descriptor-bounded, so the default stands
// in. The controller always passes the full set, and that path is unaffected.
func TestResourceLimitsFallBackToTheConstant(t *testing.T) {
	if !strings.Contains(jailerLaunch(testParams(), paths.ForVirtualMachine(testUUID)),
		"    --resource-limit no-file=1024 \\\n") {
		t.Error("an omitted --resource-arg did not fall back to no-file=1024")
	}
}

// TestEveryResourceLimitGetsItsOwnQuotedLine, for the same word-splitting reason
// the cgroup values do — the launcher owns the --resource-limit prefix, so a value
// with a space stays one argument.
func TestEveryResourceLimitGetsItsOwnQuotedLine(t *testing.T) {
	params := testParams()
	params.ResourceArguments = []string{"no-file=4096", "fsize=1 2"}

	rendered := jailerLaunch(params, paths.ForVirtualMachine(testUUID))

	want := "    --resource-limit no-file=4096 \\\n    --resource-limit 'fsize=1 2' \\\n"
	if !strings.Contains(rendered, want) {
		t.Errorf("resource limits rendered as:\n%s", rendered)
	}
	if strings.Contains(rendered, "no-file=1024") {
		t.Error("the fallback was used even though resource limits were given")
	}
}

// TestTheLauncherCarriesTheMarkerPathSleepGrepsFor. The sleep verb tells a launcher
// that predates memory snapshots from one that supports them by grepping this file
// for snapshot/READY; a rewrite that dropped or renamed that path would make every
// VM look un-sleepable, and the failure would surface as a refused sleep rather
// than as a broken provision.
func TestTheLauncherCarriesTheMarkerPathSleepGrepsFor(t *testing.T) {
	if !strings.Contains(jailerLaunch(testParams(), paths.ForVirtualMachine(testUUID)), "snapshot/READY") {
		t.Error("the launcher no longer names snapshot/READY")
	}
}

// TestTheLauncherCgroupLinesAreContiguousAndPrefixed. internal/vm's resize splices
// this run of lines in place and REFUSES a launcher whose --cgroup lines are absent
// or interleaved, rather than leaving stale memory caps behind. The two shapes have
// to agree, and this is where that is pinned.
func TestTheLauncherCgroupLinesAreContiguousAndPrefixed(t *testing.T) {
	lines := strings.Split(jailerLaunch(testParams(), paths.ForVirtualMachine(testUUID)), "\n")
	var indices []int
	for index, line := range lines {
		if strings.HasPrefix(strings.TrimLeft(line, " \t"), "--cgroup ") {
			indices = append(indices, index)
		}
	}
	if len(indices) != 3 {
		t.Fatalf("found %d --cgroup lines, want 3", len(indices))
	}
	if indices[2]-indices[0] != 2 {
		t.Errorf("the --cgroup lines are not contiguous: %v", indices)
	}
}

// TestTheMMDSPayloadIsThePythons. A warm clone's disk is never mutated offline, so
// this file is the ONLY channel its identity travels down: the freshen unit baked
// into the golden reads it from 169.254.169.254 after the resume. The hostname and
// machine-id below are the identity injection's own derivations, which is what
// makes a warm clone's identity match what a cold provision of the same UUID gets.
func TestTheMMDSPayloadIsThePythons(t *testing.T) {
	params := testParams()
	params.RoutingBaseURL = "https://atlas.example.com"
	params.PrivateAddress = "fdaa:1::5"

	got, err := mmdsMetadata(params)
	if err != nil {
		t.Fatalf("mmdsMetadata: %v", err)
	}

	assertText(t, got, `{
 "identity": {
  "uuid": "3f2504e0-4f89-41d3-9a0c-0305e82c3301",
  "hostname": "atlas-3f2504e0",
  "machine_id": "3f2504e04f8941d39a0c0305e82c3301",
  "ipv6": "2001:db8::2",
  "ipv4_cidr": "100.64.200.10/30",
  "ipv4_gateway": "100.64.200.9",
  "ssh_public_key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5 operator@atlas",
  "routing_base_url": "https://atlas.example.com",
  "private_address": "fdaa:1::5"
 }
}
`)
}

// TestTheMMDSPayloadKeepsEmptyKeys. The Python emits the key with an empty value
// rather than dropping it, and the guest's freshen unit reads a defined field
// either way — a dropped key would be a KeyError in the guest instead of a
// no-op.
func TestTheMMDSPayloadKeepsEmptyKeys(t *testing.T) {
	got, err := mmdsMetadata(testParams())
	if err != nil {
		t.Fatalf("mmdsMetadata: %v", err)
	}
	for _, key := range []string{`"routing_base_url": ""`, `"private_address": ""`} {
		if !strings.Contains(got, key) {
			t.Errorf("%s is missing from:\n%s", key, got)
		}
	}
}

// TestJSONIsNotHTMLEscaped. Go's encoder escapes `<`, `>` and `&` by default and
// Python's json.dumps does not, so an SSH key comment or a routing URL carrying one
// would differ byte for byte — and the guest would be handed & where the
// Python handed it &.
func TestJSONIsNotHTMLEscaped(t *testing.T) {
	params := testParams()
	params.RoutingBaseURL = "https://atlas.example.com/?a=1&b=2"
	params.SSHPublicKey = "ssh-ed25519 AAAA <operator@atlas>"

	got, err := mmdsMetadata(params)
	if err != nil {
		t.Fatalf("mmdsMetadata: %v", err)
	}

	if strings.Contains(got, `\u00`) {
		t.Errorf("the payload was HTML-escaped:\n%s", got)
	}
	if !strings.Contains(got, "https://atlas.example.com/?a=1&b=2") {
		t.Errorf("the routing URL did not survive verbatim:\n%s", got)
	}
}
